name: Builds the release binary

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Set up Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      - name: Install Node.js deps
        run: pnpm i
    
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

#      - name: Install Rust deps
#        run: | 
#          cd src-tauri/
#          cargo build --release

      - name: Build tauri app (installs rust deps)
        run: pnpm tauri build

      - name: Create Github Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Upload Release asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: src-tauri/target/release/fs-app.exe
          asset_name: fs-app.exe
          asset_content_type: application/octet-stream
